# Generated by Django 4.1.7 on 2023-03-18 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='markedpost',
            options={'verbose_name': 'Marked post', 'verbose_name_plural': 'Marked posts'},
        ),
        migrations.AlterModelTable(
            name='markedpost',
            table='marked posts',
        ),
    ]
