# Generated by Django 4.1.7 on 2023-03-18 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_markedpost_options_alter_markedpost_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='markedpost',
            table='marked_posts',
        ),
    ]
